# Generated by Django 3.2.16 on 2022-11-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0002_auto_20221101_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_room',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
