# Generated by Django 3.2.16 on 2022-11-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0003_auto_20221101_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
